### ISSUE TITLE
lib.php encryption

### ISSUE THREAD

**Issue by ghost** [renderse7en/dragon-scourge#1]
Hello,
Could you decrypt the lib.php? I try to bring the database part of the code up to a usable state again.

UPDATE: Nevermind, got it already. Is there anybody interested in a updated version of this script?

**Comment by aure2006** [comment]
I'm interested.

**Comment by rybussell** [comment]
Fhizban,
I've recently started working on converting this as well.. Have you done anything since decrypting the lib.php file?

**Comment by ghost** [comment]
hey there,
Not really - feel free to give it a whirl!

In fact, i picked up an older web-based game project of mine again - its far from being finished, but you can check out the progress here if you want: www.critical-hit.biz

**Comment by aure2006** [comment]
If anyone wants to deobfuscate lib.php, run this code.

``header("Content-Type: text/plain");
$file = fopen("lib.php","rb");
fgets($file,1024);
fgets($file,4096);
fread($file,372);
$c = base64_decode(strtr(fread($file,12844),
	'EnteryouwkhRHYKNWOUTAaBbCcDdFfGgIiJjLlMmPpQqSsVvXxZz0123456789+/=',
	'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
));
echo $c;
fclose($file);``

**Comment by renderse7en** [comment]
I went ahead and updated lib.php in the master branch with the decrypted version. I had to use @aure2006's code cuz I couldn't find my own original copy, so hopefully it's not missing anything. Thanks, y'all.
